### ISSUE TITLE
Tip Calculator for iPhone

### ISSUE THREAD

**Issue by dpkagrawal** [dpkagrawal/TipCalculator#1]
@nesquena and @timothy1ee Can you please review it.

**Comment by timothy1ee** [comment]
Great, thanks for the submission! Hopefully, this gave you a sense for the basic iOS development process.

The next step is to schedule a 15 minute phone interview here: https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg. Let me know if none of those slots work.

When you choose a slot, can you edit the event with your phone number? Look forward to chatting!
